services:
  new-project:
    build: .
    container_name: new-project-app
    ports:
      - "9020:9020"
    environment:
      APP_PROFILE: ${APP_PROFILE:-sandbox}
    volumes:
      - ./settings/contours/${APP_PROFILE:-sandbox}.yaml:/app/settings/contours/${APP_PROFILE:-sandbox}.yaml:ro
    restart: unless-stopped
