services:
  new-project:
    build: .
    container_name: new-project-app
    ports:
      - "9020:9020"
    environment:
      APP_PROFILE: ${APP_PROFILE:-sandbox}
    volumes:
      - ./settings/server:/app/settings/server:ro
    restart: unless-stopped
