services:
  new-project:
    image: ${DOCKER_IMAGE_NAME}
    container_name: ${DOCKER_CONTAINER_NAME}
    environment:
      APP_PROFILE: ${APP_PROFILE}
    networks:
      - easy-craft-network
    restart: unless-stopped

networks:
  easy-craft-network:
    external: true
