# settings/application-sandbox.yaml
postgres:
  host: "localhost"
  port: 5432
  database: "test_db"
  user: "test_user"
  password: "test_password"
  table_name: "Test_table"

kafka:
  bootstrap_servers: "gitlab-ci.ru:9092"
  consumer_group: "frap-llm-helper-group"
  topic_in: "frap-llm-helper-in"
  topic_out: "frap-llm-helper-out"

file_storage:
  base_path: "/data/frap-files"  # [Part1] - базовый путь
  output_dir: "/app/output"      # Папка для сохранения результатов

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
